"""initial schema

Revision ID: 828dfa848ed7
Revises: 
Create Date: 2026-03-16 15:53:49.298396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828dfa848ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependencia_id', 'nombre', name='uq_area_dependencia_nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('cuestionario_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('publicado_at', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eje_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuestionario_version_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ponderacion', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuestionario_version_id'], ['cuestionario_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodo_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('cuestionario_version_id', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['cuestionario_version_id'], ['cuestionario_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('enviada_revision_at', sa.DateTime(), nullable=True),
    sa.Column('aprobada_at', sa.DateTime(), nullable=True),
    sa.Column('cerrada_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencia.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_evaluacion.id'], ),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'dependencia_id', name='uq_evaluacion_periodo_dependencia')
    )
    op.create_table('reactivo_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eje_version_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('opciones', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eje_version_id'], ['eje_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eje_version_id', 'orden', name='uq_reactivo_eje_orden')
    )
    op.create_table('evaluacion_asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'usuario_id', 'tipo', name='uq_asignacion_evaluacion_usuario_tipo')
    )
    op.create_table('evidencia_eje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('eje_version_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archivo_nombre_original', sa.String(length=255), nullable=False),
    sa.Column('archivo_guardado', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('reemplaza_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['eje_version_id'], ['eje_version.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['reemplaza_id'], ['evidencia_eje.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacion_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('eje_version_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('atendida', sa.Boolean(), nullable=False),
    sa.Column('atendida_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['eje_version_id'], ['eje_version.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('reactivo_version_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('usuario_captura_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['reactivo_version_id'], ['reactivo_version.id'], ),
    sa.ForeignKeyConstraint(['usuario_captura_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'reactivo_version_id', name='uq_respuesta_evaluacion_reactivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta')
    op.drop_table('observacion_revision')
    op.drop_table('evidencia_eje')
    op.drop_table('evaluacion_asignacion')
    op.drop_table('reactivo_version')
    op.drop_table('evaluacion')
    op.drop_table('periodo_evaluacion')
    op.drop_table('eje_version')
    op.drop_table('notificacion')
    op.drop_table('cuestionario_version')
    op.drop_table('usuario')
    op.drop_table('area')
    op.drop_table('dependencia')
    # ### end Alembic commands ###
